### ISSUE TITLE
URL pattern matching is naive

### ISSUE THREAD

**Issue by nxvipin** [kumarshantanu/calfpath#3]
Lets assume we have the following url: `foo/:bar`.

`foo/baz` -> The value of `:bar` is `baz`
`foo/baz?match=fail` -> The value of `:bar` is `baz?match=fail` instead of `baz`

This is an obviously wrong.  The pattern match should only happen on the `path` and not the `query-string`. See the Image below (from wikipedia) on what path is and what query strings are. 

```
                    hierarchical part
        ┌───────────────────┴─────────────────────┐
                    authority               path
        ┌───────────────┴───────────────┐┌───┴────┐
  abc://username:password@example.com:123/path/data?key=value&key2=value2#fragid1
  └┬┘   └───────┬───────┘ └────┬────┘ └┬┘           └─────────┬─────────┘ └──┬──┘
scheme  user information     host     port                  query         fragment
```

I have written tests that reproduce this failure. Please `git apply` the patch (generated on current HEAD: 35841f48cb92e43999ea846ee6da66a368d756fd) below and run `lein test` to see the failing case.

```
diff --git a/test/calfpath/core_test.clj b/test/calfpath/core_test.clj
index 899063f..6b75a36 100644
--- a/test/calfpath/core_test.clj
+++ b/test/calfpath/core_test.clj
@@ -13,13 +13,21 @@


 (def user-profile-path "/user/:id/profile/:type/")
+(def path-with-params "/user/:id")


 (deftest test-->uri
   (testing "No clause"
     (let [request {:uri "/user/1234/profile/compact/"}]
       (is (= 400
-            (:status (c/->uri request))))))
+             (:status (c/->uri request))))))
+
+  (testing "Path with params"
+    (let [request {:uri "/user/1234?foo=bar"}]
+      (is (= "ID: 1234"
+            (:body (c/->uri request
+                     path-with-params          [id] {:status 200
+                                                     :body (format "ID: %s" id)}))))))
   (testing "One clause (no match)"
     (let [request {:uri "/hello/1234/"}]
       (is (= 400
```

**Comment by nxvipin** [comment]
Added `&` instead of `?` for the first query param. I am stupid.

**Comment by nxvipin** [comment]
It works in `profile` but this test still fails.

**Comment by kumarshantanu** [comment]
Calfpath being a Ring request matching library, it expects the URI to be compliant with the [Ring spec](https://github.com/ring-clojure/ring/wiki/Concepts#requests). Ring adapters split the URI and the query string before passing it to the handler, hence Calfpath need not consider the query string while matching URI.

Closing the issue. Feel free to reopen if I missed anything.
