### ISSUE TITLE
Question: How can I get a list of all available routes

### ISSUE THREAD

**Issue by avallark** [kumarshantanu/calfpath#6]
Is there a calfpath function that can return me all the available functions? The documentation doesnt mention any. This would be similar to the list that you output when there is a 400.

**Comment by kumarshantanu** [comment]
@avallark Calfpath does not make the routes list accessible at runtime. Your middleware functions may already have access to the routes list and may use it in a suitable way, e.g. https://github.com/kumarshantanu/calfpath/blob/v0.5.0/src/calfpath/route.clj#L139-L156

**Comment by kumarshantanu** [comment]
Moreover, routes are declarative data so you can just define the routes as data and access it later.
